apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1afm2s0dypf327qrm9whfwptnvuxcl75md5hc9qtddwqckd0u8eeq5fz0qy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbFpIbjdVWVVOc24rMlVZ
            TXdVWWVmbUN4c0hla1JKN2pjT2txeTMzc2pZCk9jdm5QMmNpS01uakRNd0lJeEY0
            N0xTZ3o5c0dKcHBsTTNkN3VoN25QYjQKLS0tIHFvTURiL1VsTnVsK3BDbEQ3aG0x
            ZHFKbDNoRUZxdERXb3h1eGVuQWVaaVkK9zfHhHp8TDCNEpIAxt+lc1/iitttMMSd
            mbgMSBQj5BI4j+H83UV4fSrFODIimEMT50f9+XCAvAadaXpQzrD/Xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T18:53:30Z"
    mac: ENC[AES256_GCM,data:blccsu13bhMGESlSsJt4wz74Tu4/AhYI2EFQqS/jmHxJIKExNhG0iZ6BF7rPaOT5RZCIFG30cCiOAJQ3ooPc5o/0RAZ5uxzJPfbygBlHTSVVirzhTPF5G6ZQTekhWEB7jd1gqBUhTCnLQIv1BMTGI7WsI7y2YYhgYCiW7VA8mw4=,iv:S5w6pO1HAZNK23xRmYIu6bpH4+sSrK52T51xLsNwS8k=,tag:FiT6WPCruGLxewQIzrDTbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
