apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjumf0zqx4e7k7jszhczhrharc83tjz825xukdqetjjq0fwsd6sw4n7vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdExxbHo5Qkx3dVAwTXN2
            ZUZYaWkrR1pRemEyeUg1UXRCT3MydUNxbkY0CkhTNitGeVh6OUIvM0NNZU5LaWpk
            SVhxTm0zWWJPVzd3dUo5MG9mYXNlZncKLS0tIHpydUJJMURyZnVlZjFsRk80MTlk
            dy9SaERSSC9lbUI2MWY4bnVERDl0clEKPllSOyv6d1rBkSjVQyogHBYF2M1fVW6y
            OGfniigGc5eFftJEzrrwu7LzH+BWvG92+23ASFYNKRFlD+WYz3dUGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T19:53:22Z"
    mac: ENC[AES256_GCM,data:NLiDQPgyRii7mZhuCpJoqvaGukkVA6/Z2BnUP4/CYUYEm+PbQtWOAz+BeUyBFaTdHA8CWTyLej274YiClPPMNWKGdn2e3NsYTMl+6C4SmDAiYv13d/jrly5I/heiaZoZ36DkGWTYL+QKBB5qwt1/30T2ZSXGIH+VCC26bFKvJ9w=,iv:sWmSOlhDMnCKc69DTiY4G4C19+FAGtyDnloZkYOq2Hc=,tag:fDhvpBvHhoRxiEaWdVlRbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
