apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18vylkffzxmp48wmse8h69dzhq83ve4t22s9cxucj566eurzdad3qp9hea4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtT28zYUpUZzJaeXdndVdx
            SmtIcmhiQmR6SVFxZStLYkVVbXkzNGRHZ1RvClFyTTJNZDFKcEs3QnJNbUQ1RlZB
            dXdzK0l2cHFTWlF6Umd1LzVvNzgwdncKLS0tIE5Xd0lYZ203dGlwVTJqdlMza0l1
            Rk4yL2hQWlF3U1JRSXRhT0U5ZEJNMkEKYyg9v7QBcVEtY6gX6ZQBP23K0EQ3YMpZ
            P2rnFybjHAAnQ/02xf4itgJLLEzhSpGzaWnpY5PW6R4dK2tBNrLOFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T18:50:38Z"
    mac: ENC[AES256_GCM,data:ATDmY1e+Kb18hKOyvtVRxNjy0viwETXjNdXS0EHuuYpqDdG8h0Ab2C8ccxcj8d80K0nZiSapK3hpuyRWq5aMzotAMZi8XcWieJD17igSUF7Jd4G2srXekiMvVegIBfpen3prTxhv4wM4fRPEojEg6SzS5jf03jHy4tn1FBaWA4E=,iv:euHfkTBVFdXmQDM/a925ZiZ1S7KEdwiWQHZY5j8s1Nc=,tag:rhxAzuVUebXox/EEEHz2Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
