apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:DV4CjQsZ0Ck0sx/xGc2Bhb0KI8AYy3FRRh7yS2q0Vt8=,iv:7g/TEKgVYHxvKuHtCPheNN50AHtSdr/jSSBzl5cM8is=,tag:qzwftTPdoTF+i6WZ9p5yOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xzjumf0zqx4e7k7jszhczhrharc83tjz825xukdqetjjq0fwsd6sw4n7vr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZjVtMStySjBwTXUybC9L
            M2IxMnBubG9MZFh0OWRyQnFMK1NlR2t3SVM0ClozSndudTV0L3FRNXQzeHp3UXU5
            WmR0Q3p1a3hVZkJwbkVZM3ZRVDFINlEKLS0tIFgrOFZjaEo3MjB5QnduaHZzUmJT
            YitXMHVoYVVsWjV1SzlLNTVBOHpYMXcKuTUIfT3Rx7HmKRMpOqRjkEDiXWqylTjQ
            SOYIsZJ6GgZWz6vv5OIt6HGYsrW564oCYm7mGv0T3SKv3tdfKGjz+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T19:03:58Z"
    mac: ENC[AES256_GCM,data:emdtG4ySsnqp4TQco+R/vg/Fk16THHgri1Zi509q/vFBbd29u+jV69bNjZ8hrOiM4ieKRC9ZDGEua/8Z95Sx42hKV4M6NBFrKDaFazT7fapA9DEQHfyIrsG9i8mwGLov+B4bRqqJNG8bktMr06whGtnrII2hzLYPn/4cHiCf4EM=,iv:IthRt6uIwMiLYC4Z1ZWIgahxNrrn615OsbA7TfLmO6o=,tag:D7P2JMEe2p01b0bcb5ExfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
