apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18vylkffzxmp48wmse8h69dzhq83ve4t22s9cxucj566eurzdad3qp9hea4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYWNabkgrcjd0V0NqYmNp
            UmZhTHFWemZ3QUE1RVBkb2g4ZEF4SkNIeTNJClcwSDY5dlVyWWZrWkhYQldQdnRm
            dkdSamkycWpjQWtvRCs2SEJ5UE5UN28KLS0tIERJRjlCelY2c0Z2Lzh2d0NWdVhQ
            ZTBFV0tGN3E4bFpPTllRaUVXVUtCK00KVGFvBe+fixYgFVozeS+dzrkNtkb9+/sl
            OlgPNjNWvTynMK9yn0Ak3+m/StG0SZFwMUrZwql/STFyUWI0DdMweA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T18:44:27Z"
    mac: ENC[AES256_GCM,data:qSJJkFLzxTT1WIcVSoyR+W5D+KzaDkyCy6foAs/kRBPFawzyV0NLpSm5VdxZHNT5lMaZAwZefqlAjkGbLxRTKgIVAXklVMCFSHB2f0Z9A3A71Aye9TudpAnTFzcCNvUtkx7rsJNs8NIF+uPSvf0ptG4YbFGNo3JNvXBmEpNwM80=,iv:scVGpcEYzdvhcgNbWAONc8UTYWuo3gpd3WgvJxgrxGo=,tag:0eo/djXPwNqBZ0vH7v172A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
