apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18vylkffzxmp48wmse8h69dzhq83ve4t22s9cxucj566eurzdad3qp9hea4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtemE4bnR5N2lHeUl4Zmh6
            b0piSXd0R3EvVkNvN3pQdWt5bXZHaTZlNGswCnR5dHlxam1jblFOck9EMmdDN3lM
            QTZuZEFzeGwxQVlJOSt3cXBUMDNGbVUKLS0tIGpqbDRzTDh4azJtMmpjZ1RMeVlD
            b1NYWVBSNWZQaWRyaDlpSmt2NVYrTVkKkE97ZUvgWS/wgLbm6br1/kkWioQBNKW0
            k4bqB6G9zRx0lmFvao0vo2kKnxlBC+GDXPbKf9zf1D+AfRRMJl1cpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T18:48:41Z"
    mac: ENC[AES256_GCM,data:rLP+76ORLzBD4l044mR9f9+Q0ErfOgDZ0+Lc6iYQnw+6GcgG+RRYtkpPfaWlAnQmqsaXU2XV/mhaOUgBe8B7nDviLhUbXYMwI2BUiDnDxEJfhmBOu/BOkIogk2J/m5fcRSAHzbgV7qUu3H/5gAM51CqxpYDqCTNZs22cSvTpNJo=,iv:SkKAzNKlcUWZj77NOFVeJmdZfXsKERH7e/HfdZqITpc=,tag:4ctsrA8HI+tadjuiHfP04g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
